import sys
import pandas as pd
"""
uses the csv generated by https://github.com/mindcruzer/rbc-statement-to-csv
"""
def transform_rbc(rbc):
    rbc_transformed = rbc.loc[:,["Transaction Date", "Description", "Amount"]]
    rbc_transformed.rename(columns={"Transaction Date": "date", "Description": "description", "Amount": "amount"}, inplace=True)
    rbc_transformed["account"] = "rbc"
    return rbc_transformed

"""
uses the csv generated from the td easy web app
"""
def transform_td(td):
    td_transformed = td.loc[:,["date", "description"]]
    td_transformed["amount"] = td["deposit"].fillna(0) - td["withdraw"].fillna(0)
    td_transformed["account"] = "td"
    return td_transformed

input_csv_path = sys.argv[1]
type = sys.argv[2]
output_csv_path = sys.argv[3]
params = {
    "td": {
        "transform_func": transform_td,
        "date_cols": ["date"]
    },
    "rbc": {
        "transform_func": transform_rbc,
        "date_cols": ["Transaction Date", "Posting Date"]
    }
}
csv = pd.read_csv(input_csv_path, parse_dates=params[type]["date_cols"])

output = params[type]["transform_func"](csv)

output.sort_values(by=["date"]).to_csv(output_csv_path, index=False)